---
name: checks

on: [push]

jobs: 
    test-lint:
        name: Test Lint
        runs-on: ubuntu-latest
        env:
            ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        steps:
            -   name: login to Docker HUb
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USER }}
                    password: ${{ secrets.DOCKERHUB_TOKEN}}
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Tezt
                run: docker-compose run --rm app sh -c "python manage.py test"
            -   name: Lint
                run: docker-compose run --rm app sh -c "flake8"